export const USER_REPOSITORY = 'USERS_REPOSITORY';
export const FEED_REPOSITORY = 'FEEDS_REPOSITORY';
export const PAYMENT_PROVIDER = 'PAYMENTS_REPOSITORY';
export const MEMBER_PROVIDER = 'MEMBERS_REPOSITORY';
export const MEMBERTIER_PROVIDER = 'MEMBERTIERS_REPOSITORY';
export const MEMBERCOUPON_PROVIDER = 'MEMBERCOUPONS_REPOSITORY';

export const ADMIN_PROVIDER = 'ADMINS_REPOSITORY';
export const EVENTCATEGORY_PROVIDER = 'EVENTCATEGORY_REPOSITORY';
export const ARTICLE_PROVIDER = 'ARTICLE_REPOSITORY';
export const CART_PROVIDER = 'CART_REPOSITORY';

export const ARTICLECATEGORY_PROVIDER = 'ARTICLECATEGORY_REPOSITORY';
export const ONLINEPAYMENT_PROVIDER = 'ONLINEPAYMENT_REPOSITORY';
export const DELIVERY_PROVIDER = 'DELIVERY_REPOSITORY';
export const DELIVERY_FREESETUP_PROVIDER = 'DELIVERY_FREESETUP_REPOSITORY';
export const CONTENT_PROVIDER = 'CONTENT_PROVIDER';

export const PRODUCTCATEGORY_PROVIDER = 'PRODUCTCATEGORY_REPOSITORY';
export const PRODUCTTAG_PROVIDER = 'PRODUCTTAG_REPOSITORY';
export const PRODUCT_COLLECTION_PROVIDER = 'PRODUCT_COLLECTION_REPOSITORY';
export const PRODUCT_COLLECTION_ITEM_PROVIDER =
  'PRODUCT_COLLECTION_ITEM_REPOSITORY';
export const DISCOUNT_PROVIDER = 'DISCOUNT_REPOSITORY';
export const PRODUCT_PROVIDER = 'PRODUCT_REPOSITORY';
export const PRODUCT_OPTION_PROVIDER = 'PRODUCT_OPTION_REPOSITORY';
export const PRODUCT_MEDIA_PROVIDER = 'PRODUCT_MEDIA_REPOSITORY';
export const PRODUCT_SAVED_PROVIDER = 'PRODUCT_SAVED_REPOSITORY';

export const VOUCHER_PROVIDER = 'VOUCHER_REPOSITORY';
export const VOUCHER_SETTING_PROVIDER = 'VOUCHER_SETTING_PROVIDER';
export const COUPON_PROVIDER = 'COUPON_REPOSITORY';
export const COUPON_TIER_PROVIDER = 'COUPON_TIER_REPOSITORY';

export const EVENT_PROVIDER = 'EVENT_REPOSITORY';
export const EVENT_TICKET_PROVIDER = 'EVENT_TICKET_REPOSITORY';
export const EVENT_TIMESLOT_REPOSITORY = 'EVENT_TIMESLOT_REPOSITORY';

export const EVENT_COLLECTION_PROVIDER = 'EVENT_COLLECTION_REPOSITORY';
export const EVENT_FORM_REPOSITORY = 'EVENT_FORM_REPOSITORY';
export const TRANSACTION_PROVIDER = 'TRANSACTION_REPOSITORY';
export const TRANSACTION_PRODUCT_PROVIDER = 'TRANSACTION_PRODUCT_REPOSITORY';
export const TRANSACTION_PRODUCT_DETAIL_PROVIDER =
  'TRANSACTION_PRODUCT_DETAIL_REPOSITORY';

export const NOTIFICATION_PROVIDER = 'NOTIFICATION_REPOSITORY';
export const LOG_NOTIFICATION_PROVIDER = 'LOG_NOTIFICATION_REPOSITORY';
export const MESSAGE_PROVIDER = 'MESSAGE_REPOSITORY';
export const MESSAGE_DETAIL_PROVIDER = 'MESSAGE_DETAIL_REPOSITORY';

export const POINTLOG_PROVIDER = 'POINTLOG_REPOSITORY';

export const EVENT_ITEM_PROVIDER = 'EVENT_ITEM_REPOSITORY';
export const TRANSACTION_EVENT_PROVIDER = 'TRANSACTION_EVENT_PROVIDER';

export const jwtConstants = {
  secret: 'secretKey',
};

export const SEQUELIZE = 'SEQUELIZE';
export const DEVELOPMENT = 'development';
export const TEST = 'test';
export const PRODUCTION = 'production';

export const RESPONSES = {
  DATA_FOUND: 'Data found',
  DATA_NOTFOUND: 'Data not found',
  DATA_CREATED: 'Data added successfully',
  DATA_UPDATED: 'Data successfully updated',
  DATA_DELETED: 'Data deleted successfully',
  FAIL_DELETED: 'Fail when delete data',
};
