version: '3.8'

services:
  prod:
    container_name: yingshun_be
    image: registry.digitalocean.com/so-thai/yingshun-be:latest
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    networks:
      - locnet
    restart: unless-stopped

networks:
  locnet:
    driver: bridge
